<template>
    <ion-page style="overflow-y: scroll;">


        <ion-grid style="margin-top:60px">
            <ion-row>
                <ion-col>
                    <h1 style="text-align: center;">How Power Plants Work</h1>
                </ion-col>
            </ion-row>
            <ion-row style="margin-top:20px">A nuclear reactor produces and controls the release of energy from
                splitting the atoms of certain
                elements. In a nuclear power reactor, the energy released is used as heat to make steam to generate
                electricity.</ion-row>
            <ion-row style="margin-top:20px">Power Plants use a process called Nuclear fission, which is the process of
                splitting atomic nuclei, was discovered in 1938 by Otto Hahn and Fritz Strassmann. While the first
                self-sustaining nuclear chain reaction was achieved in 1942 at the University of Chicago. The first
                electricity generated by a nuclear power plant was in 1951 at EBR-I (Experimental Breeder Reactor-I) in
                Idaho. </ion-row>

            <ion-row>
                <img :src="nuke" style="max-width: 400px; align-self: center; border-radius: 50px;"></img>


            </ion-row>
        </ion-grid>

        <ion-grid style="margin-top:60px">
            <ion-row>
                <ion-col>
                    <h1 style="text-align: center;">How Wind Power Work</h1>
                </ion-col>
            </ion-row>
            <ion-row style="margin-top:20px">
                Wind turbines convert the kinetic energy of moving air into mechanical energy, which is then transformed
                into electricity by a generator. The spinning blades turn a shaft connected to the generator, producing
                clean, renewable energy.


            </ion-row>
            <ion-row style="margin-top:20px">
                The earliest known wind-powered machines were used in Persia around 500–900 AD to grind grain and pump
                water. Modern wind turbines trace back to Danish inventor Poul la Cour, who built the first
                electricity-generating wind turbine in the late 1800s.

            </ion-row>
            <ion-row>
                <img :src="wind" style="max-width: 300px; align-self: center; border-radius: 50px;"></img>


            </ion-row>
        </ion-grid>

        <ion-item>
            <p>
            </p>
        </ion-item>

    </ion-page>
</template>

<script setup lang="ts">
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonItem, IonImg } from '@ionic/vue';
import { Ref } from 'vue';
let wind = new URL('../assets/hiwwindpower.png', import.meta.url).href
let nuke = new URL('../assets/hiwpowerplant.png', import.meta.url).href

</script>

<style scoped>
center {
    text-align: center;
}

#container {
    text-align: center;
    position: absolute;
    left: 0;
    right: 0;
    top: 50%;
    transform: translateY(-50%);
}

#container strong {
    font-size: 20px;
    line-height: 26px;
}

#container p {
    font-size: 16px;
    line-height: 22px;
    color: #8c8c8c;
    margin: 0;
}

#container a {
    text-decoration: none;
}

img {
    width: 100%;
    height: auto;
}
</style>