<template>
    <ion-page>


        <ion-grid style="margin-top:60px">
            <ion-row>
                <ion-col>
                    <h1 style="text-align: center;">How Power Plants Work</h1>
                </ion-col>
            </ion-row>
            <ion-row style="margin-top:20px">A nuclear reactor produces and controls the release of energy from splitting the atoms of certain
                elements. In a nuclear power reactor, the energy released is used as heat to make steam to generate
                electricity.</ion-row>
                <ion-row style="margin-top:20px">Power Plants use a process called Nuclear fission, which is the process of splitting atomic nuclei, was discovered in 1938 by Otto Hahn and Fritz Strassmann. While the first self-sustaining nuclear chain reaction was achieved in 1942 at the University of Chicago. The first electricity generated by a nuclear power plant was in 1951 at EBR-I (Experimental Breeder Reactor-I) in Idaho. </ion-row>
        </ion-grid>



        <ion-item>
            <p>
            </p>
        </ion-item>

    </ion-page>
</template>

<script setup lang="ts">
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonItem, IonImg } from '@ionic/vue';
import { Swiper, SwiperSlide } from 'swiper/vue';
import { register } from 'swiper/element/bundle';
register();
import { Ref } from 'vue';

</script>

<style scoped>
center {
    text-align: center;
}

#container {
    text-align: center;
    position: absolute;
    left: 0;
    right: 0;
    top: 50%;
    transform: translateY(-50%);
}

#container strong {
    font-size: 20px;
    line-height: 26px;
}

#container p {
    font-size: 16px;
    line-height: 22px;
    color: #8c8c8c;
    margin: 0;
}

#container a {
    text-decoration: none;
}

img {
    width: 100%;
    height: auto;
}
</style>